export const GENERAL_ENRICHMENT = {
  account: { zh: "账户；说明；叙述；理由", en: "a record of money, a report, or an explanation", ex: "The account of the trip was short and clear.", exz: "这次旅行的叙述简短而清楚。" },
  act: { zh: "行为；行动；法令；表演", en: "something that is done or a part of a performance", ex: "A kind act may give comfort to a friend.", exz: "一个善意的行为可能给朋友带来安慰。" },
  addition: { zh: "增加；加法；附加物", en: "something added or the process of adding", ex: "The addition of one room made the house better.", exz: "增加一个房间让这所房子更好用了。" },
  adjustment: { zh: "调整；调节；适应", en: "a small change made to improve fit or use", ex: "A small adjustment made the machine quiet.", exz: "一个小调整让机器安静了。" },
  advertisement: { zh: "广告；公告；宣传信息", en: "a public notice made to sell or announce something", ex: "The advertisement gave the price of the new coat.", exz: "广告给出了新外衣的价格。" },
  agreement: { zh: "协议；同意；一致", en: "a shared decision or a state of being in accord", ex: "The agreement brought peace to the two families.", exz: "这份协议给两个家庭带来了平和。" },
  air: { zh: "空气；空中；气氛", en: "the gas around the earth or the feeling of a place", ex: "Fresh air came through the open window.", exz: "新鲜空气从开着的窗户进来。" },
  amount: { zh: "数量；总额；程度", en: "how much there is of something", ex: "The amount of water in the pot was enough.", exz: "锅里的水量足够了。" },
  amusement: { zh: "娱乐；消遣；有趣的事", en: "pleasure or something that makes people laugh or relax", ex: "The small show gave the children much amusement.", exz: "这个小表演给孩子们带来很多乐趣。" },
  animal: { zh: "动物；兽类", en: "a living creature that is not a plant", ex: "The animal came near the water at night.", exz: "这只动物夜里来到水边。" },
  answer: { zh: "回答；答案；回应", en: "something said or done in reply to a question", ex: "Write your answer under the question.", exz: "把你的答案写在问题下面。" },
  apparatus: { zh: "器具；设备；装置", en: "a set of tools or equipment for a purpose", ex: "The apparatus on the table was used for the test.", exz: "桌上的装置用于这次测试。" },
  approval: { zh: "赞成；认可；批准", en: "acceptance or a favorable opinion", ex: "The plan was sent to the committee for approval.", exz: "这个计划被送交委员会批准。" },
  argument: { zh: "争论；论点；理由", en: "a disagreement or a reason given for an idea", ex: "The argument ended when the facts were clear.", exz: "事实清楚后，争论结束了。" },
  art: { zh: "艺术；技艺；美术", en: "creative work made with skill and imagination", ex: "The art on the wall showed a quiet river.", exz: "墙上的画表现了一条安静的河。" },
  attack: { zh: "攻击；袭击；抨击", en: "a forceful act against a person, place, or idea", ex: "The attack on the town came before morning.", exz: "对城镇的袭击发生在清晨之前。" },
  attempt: { zh: "尝试；企图；努力", en: "an effort to do something", ex: "Her first attempt at the work was careful.", exz: "她第一次尝试这项工作时很认真。" },
  attention: { zh: "注意；关注；照料", en: "careful thought, notice, or care", ex: "Give attention to the sound of each word.", exz: "注意每个词的发音。" },
  attraction: { zh: "吸引；吸引力；有吸引力的事物", en: "the power to draw interest or bring things together", ex: "The garden was the main attraction of the house.", exz: "花园是这所房子的主要吸引点。" },
  authority: { zh: "权力；权威；主管机构", en: "the right or power to give orders or make decisions", ex: "The local authority made a new road rule.", exz: "当地主管机构制定了一条新的道路规则。" },
  back: { zh: "背部；后面；返回处", en: "the rear part of a body, object, or place", ex: "Put the mark on the back of the card.", exz: "把标记写在卡片背面。" },
  balance: { zh: "平衡；余额；天平", en: "an even state, remaining amount, or weighing device", ex: "Good balance kept the boat steady.", exz: "良好的平衡让小船保持稳定。" },
  base: { zh: "底部；基础；基地", en: "the bottom support or main starting point", ex: "The base of the lamp is made of brass.", exz: "这盏灯的底座是黄铜做的。" },
  behavior: { zh: "行为；举止；表现", en: "the way a person, animal, or thing acts", ex: "The child's behavior was quiet during the meeting.", exz: "会议期间这个孩子的行为很安静。" },
  belief: { zh: "信念；相信；看法", en: "an idea accepted as true", ex: "His belief gave him hope in a hard year.", exz: "他的信念让他在艰难的一年里有了希望。" },
  birth: { zh: "出生；诞生；起源", en: "the beginning of life or the start of something", ex: "The birth of the baby brought great joy.", exz: "这个婴儿的出生带来了极大的喜悦。" },
  bit: { zh: "一点；小片；少量", en: "a small piece or amount", ex: "A bit of bread was left on the plate.", exz: "盘子里还剩一点面包。" },
  bite: { zh: "咬；一口；咬伤", en: "an act of cutting with the teeth", ex: "The dog gave the ball a hard bite.", exz: "狗用力咬了一口球。" },
  blood: { zh: "血；血液", en: "the red liquid that moves through the body", ex: "A small cut brought blood to his finger.", exz: "一个小伤口让他的手指出了血。" },
  blow: { zh: "打击；一击；吹动", en: "a hit or a movement of air", ex: "A strong blow of wind shut the door.", exz: "一阵强风把门关上了。" },
  body: { zh: "身体；主体；物体", en: "the physical form of a person, animal, or thing", ex: "The body needs rest after hard work.", exz: "身体在辛苦工作后需要休息。" },
  brass: { zh: "黄铜；黄铜器", en: "a yellow metal made from copper and zinc", ex: "The old key was made of brass.", exz: "这把旧钥匙是黄铜做的。" },
  bread: { zh: "面包；食物", en: "a common food made from flour and baked", ex: "Warm bread was on the kitchen table.", exz: "厨房桌上有温热的面包。" },
  breath: { zh: "呼吸；一口气", en: "air taken into or sent out from the lungs", ex: "Take a deep breath before you speak.", exz: "说话前深吸一口气。" },
  brother: { zh: "兄弟；同伴", en: "a male child of the same parents or a close companion", ex: "My brother sent me a letter from the city.", exz: "我兄弟从城里给我寄来一封信。" },
  building: { zh: "建筑物；建造", en: "a structure with walls and a roof", ex: "The school building stands near the river.", exz: "学校建筑在河边。" },
  burn: { zh: "烧伤；燃烧；灼痛", en: "damage from fire or heat, or the act of burning", ex: "The burn on his hand needed care.", exz: "他手上的烧伤需要处理。" },
  burst: { zh: "爆裂；突然爆发", en: "a sudden break or sudden release", ex: "A burst of rain came after the thunder.", exz: "雷声之后突然下起一阵雨。" },
  business: { zh: "生意；事务；工作", en: "work, trade, or an important matter", ex: "Her business in the market starts early.", exz: "她在市场上的生意开始得很早。" },
  butter: { zh: "黄油；奶油", en: "a soft yellow food made from milk", ex: "Put a little butter on the warm bread.", exz: "在热面包上放一点黄油。" },
  canvas: { zh: "帆布；画布", en: "strong cloth used for sails, tents, or painting", ex: "The tent was made of heavy canvas.", exz: "帐篷是用厚帆布做的。" },
  care: { zh: "照料；小心；关心", en: "attention given to safety, health, or need", ex: "The old animal needs special care.", exz: "这只老动物需要特别照料。" },
  cause: { zh: "原因；事业；导致", en: "the reason for something or a purpose people support", ex: "The cause of the noise was the engine.", exz: "噪声的原因是发动机。" },
  chalk: { zh: "粉笔；白垩", en: "soft white material used for writing on a board", ex: "The teacher wrote the word with chalk.", exz: "老师用粉笔写下这个词。" },
  chance: { zh: "机会；可能性；偶然", en: "an opportunity or the possibility that something may happen", ex: "This is a good chance to ask a question.", exz: "这是提问的好机会。" },
  change: { zh: "变化；改变；零钱", en: "a difference, an act of making different, or small money", ex: "A change in the weather made the road wet.", exz: "天气变化让道路变湿了。" },
  cloth: { zh: "布；织物；布料", en: "material made by weaving threads", ex: "The table was covered with clean cloth.", exz: "桌子盖着干净的布。" },
  coal: { zh: "煤；煤块", en: "black fuel taken from the earth and burned for heat", ex: "Coal kept the small room warm.", exz: "煤让这个小房间保持温暖。" },
  color: { zh: "颜色；色彩；给……着色", en: "the appearance of things as red, blue, green, and so on", ex: "The color of the sky changed before sunset.", exz: "日落前天空的颜色变了。" },
  comfort: { zh: "舒适；安慰；慰藉", en: "ease, relief, or a feeling of being helped", ex: "A warm fire gave comfort after the storm.", exz: "暴风雨后，温暖的火给人安慰。" },
  committee: { zh: "委员会；小组；办事机构", en: "a group chosen to consider or manage a matter", ex: "The committee met before the public meeting.", exz: "委员会在公开会议前开了会。" },
  company: { zh: "公司；陪伴；同伴", en: "a business group or the state of being with others", ex: "The company made tools for the farms near town.", exz: "这家公司为镇附近的农场制造工具。" },
  comparison: { zh: "比较；对照；比拟", en: "the act of looking at two things to see likeness and difference", ex: "A comparison of the two roads showed which was shorter.", exz: "比较两条路后可以看出哪条更短。" },
  competition: { zh: "竞争；比赛；竞赛", en: "an event or condition in which people try to do better than others", ex: "The writing competition brought many students together.", exz: "写作比赛让许多学生聚到一起。" },
  condition: { zh: "状况；条件；情形", en: "the state of something or a requirement for something", ex: "The condition of the road was poor after the rain.", exz: "雨后道路状况很差。" },
  connection: { zh: "连接；关系；联系", en: "a link or relation between people, things, or ideas", ex: "There is a clear connection between heat and steam.", exz: "热和蒸汽之间有明显联系。" },
  control: { zh: "控制；管理；支配", en: "the power to direct or limit something", ex: "Good control of the machine made the work safe.", exz: "良好控制机器让工作更安全。" },
  cook: { zh: "厨师；做饭的人；烹调", en: "a person who prepares food or the act of preparing it", ex: "The cook put rice and soup on the table.", exz: "厨师把米饭和汤放到桌上。" },
  copper: { zh: "铜；铜器", en: "a reddish-brown metal used for wires and vessels", ex: "The old pot was made of copper.", exz: "这只旧锅是铜做的。" },
  copy: { zh: "副本；复制品；抄写", en: "something made to be the same as another thing", ex: "Make a clean copy of the letter.", exz: "把这封信清楚地誊写一份。" },
  cork: { zh: "软木；瓶塞", en: "light material from tree bark, often used as a stopper", ex: "The cork kept the bottle shut.", exz: "软木塞让瓶子保持封闭。" },
  cotton: { zh: "棉花；棉布；棉制品", en: "soft white fiber used to make thread and cloth", ex: "The shirt was made from clean cotton.", exz: "这件衬衫是用干净棉布做的。" },
  cough: { zh: "咳嗽；咳声", en: "a sudden forceful sound made by pushing air from the throat", ex: "His cough was worse in the cold morning.", exz: "寒冷的早晨他的咳嗽更严重。" },
  country: { zh: "国家；乡村；地区", en: "a nation or land outside large towns", ex: "The country has many rivers and high mountains.", exz: "这个国家有许多河流和高山。" },
  cover: { zh: "盖子；覆盖物；封面", en: "something placed over or around a thing for protection", ex: "Put the cover on the box before the dust comes in.", exz: "灰尘进来前把盖子盖在箱子上。" },
  crack: { zh: "裂缝；破裂声；裂开", en: "a narrow break or a sharp breaking sound", ex: "A crack in the glass let in cold air.", exz: "玻璃上的裂缝让冷空气进来了。" },
  credit: { zh: "信用；赊账；功劳", en: "trust in payment, public praise, or a record of money owed", ex: "The shop gave him credit until the end of the week.", exz: "商店允许他赊账到周末。" },
  crime: { zh: "犯罪；罪行", en: "an act against the law", ex: "The crime was reported to the local authority.", exz: "这起罪行被报告给当地主管机构。" },
  crush: { zh: "压碎；拥挤；挤压", en: "a strong pressure that breaks or crowds something", ex: "The crush of people made the street hard to cross.", exz: "人群拥挤让街道难以穿过。" },
  cry: { zh: "哭声；喊叫；哭泣", en: "a loud call or the act of weeping", ex: "A cry came from the child in the next room.", exz: "隔壁房间传来孩子的哭声。" },
  current: { zh: "水流；电流；当前的趋势", en: "a flow of water or electricity, or the present movement of events", ex: "The current carried the small boat down the river.", exz: "水流把小船带到河下游。" },
  curve: { zh: "曲线；弯曲；弧形", en: "a line or shape that bends smoothly", ex: "The road made a curve near the hill.", exz: "道路在山边形成一个弯道。" },
  damage: { zh: "损害；破坏；损失", en: "harm done to a person, thing, or place", ex: "The storm did damage to the roof.", exz: "暴风雨损坏了屋顶。" },
  danger: { zh: "危险；威胁", en: "the possibility of harm or loss", ex: "There is danger on the broken bridge.", exz: "这座坏桥上有危险。" },
  daughter: { zh: "女儿", en: "a female child in relation to her parents", ex: "His daughter helped him in the garden.", exz: "他的女儿在花园里帮他。" },
  day: { zh: "一天；白天；日子", en: "a period of twenty-four hours or the time of light", ex: "The day was clear after a night of rain.", exz: "下了一夜雨后，这一天很晴朗。" },
  death: { zh: "死亡；终止", en: "the end of life", ex: "The death of the old tree left an open space.", exz: "老树死后留下了一块空地。" },
  debt: { zh: "债务；欠款；人情债", en: "money or duty owed to another person", ex: "He paid his debt after the harvest.", exz: "收成之后他还清了债务。" },
  decision: { zh: "决定；决断；结论", en: "a choice made after thought", ex: "The decision was made after a long discussion.", exz: "长时间讨论后作出了决定。" },
  degree: { zh: "程度；度数；学位", en: "a level, amount, or measure", ex: "The heat went up by one degree.", exz: "温度升高了一度。" },
  design: { zh: "设计；图案；计划", en: "a plan or pattern made before something is built", ex: "The design of the bridge was simple and strong.", exz: "这座桥的设计简单而坚固。" },
  desire: { zh: "愿望；欲望；想要", en: "a strong wish for something", ex: "Her desire for knowledge made her read every night.", exz: "她对知识的渴望让她每晚读书。" },
  destruction: { zh: "毁灭；破坏；摧毁", en: "the act or result of destroying something", ex: "The fire caused the destruction of the old store.", exz: "大火毁掉了那家旧商店。" },
  detail: { zh: "细节；小部分；详述", en: "a small part of a larger whole", ex: "Every detail of the map was carefully drawn.", exz: "地图的每个细节都画得很仔细。" },
  development: { zh: "发展；成长；开发", en: "growth, progress, or a new stage of change", ex: "The development of the town was slow but steady.", exz: "这座城镇的发展缓慢但稳定。" },
  digestion: { zh: "消化；理解吸收", en: "the process by which food is changed in the body", ex: "A quiet walk may help digestion after a meal.", exz: "饭后安静散步可能有助于消化。" },
  direction: { zh: "方向；指导；指令", en: "the line of movement or guidance for action", ex: "The guide pointed in the direction of the harbor.", exz: "向导指向港口的方向。" },
  discovery: { zh: "发现；被发现的事物", en: "the act of finding something not known before", ex: "The discovery of clean water changed the village.", exz: "干净水源的发现改变了村庄。" },
  discussion: { zh: "讨论；商议", en: "a serious talk about a subject", ex: "The discussion helped us make a better plan.", exz: "讨论帮助我们制定了更好的计划。" },
  disease: { zh: "疾病；病害", en: "an illness or harmful condition in a body or plant", ex: "The disease spread quickly through the animals.", exz: "这种疾病在动物中迅速传播。" },
  disgust: { zh: "厌恶；反感", en: "a strong feeling of dislike or revulsion", ex: "The bad smell filled him with disgust.", exz: "难闻的气味让他十分厌恶。" },
  distance: { zh: "距离；远处；间隔", en: "the amount of space between two points", ex: "The distance between the two towns is short.", exz: "这两个城镇之间的距离很短。" },
  distribution: { zh: "分配；分布；发放", en: "the act of giving or spreading things among people or places", ex: "The distribution of bread began in the morning.", exz: "面包的发放从早上开始。" },
  division: { zh: "分割；部门；除法；分歧", en: "a separation into parts or a part of an organization", ex: "The division of the land caused an argument.", exz: "土地的分割引发了争论。" },
  doubt: { zh: "怀疑；疑问；不确定", en: "a feeling of uncertainty about truth or action", ex: "There was some doubt about the answer.", exz: "人们对这个答案有些怀疑。" },
  drink: { zh: "饮料；喝；饮用", en: "liquid taken into the mouth or the act of taking it", ex: "A warm drink gave comfort in the cold room.", exz: "一杯热饮在寒冷房间里带来安慰。" },
  driving: { zh: "驾驶；推动；驱使", en: "the act of controlling a vehicle or forcing movement", ex: "Careful driving is necessary on this narrow road.", exz: "在这条狭窄道路上必须小心驾驶。" },
  dust: { zh: "灰尘；尘土", en: "fine dry powder from earth or old material", ex: "Dust covered the table after the long summer.", exz: "漫长夏天之后，桌子上落满灰尘。" },
  earth: { zh: "地球；土地；泥土", en: "the world, soil, or ground", ex: "The smell of wet earth came after the rain.", exz: "雨后传来湿泥土的气味。" },
  edge: { zh: "边缘；刀口；优势", en: "the outside line of a surface or a sharp side", ex: "Do not put the cup near the edge of the table.", exz: "不要把杯子放在桌边。" },
  education: { zh: "教育；培养；学习过程", en: "the process of teaching and learning", ex: "Education gave the children a wider view of the world.", exz: "教育让孩子们对世界有了更广阔的认识。" },
  effect: { zh: "效果；影响；结果", en: "a result or change caused by something", ex: "The medicine had a quick effect on the pain.", exz: "这种药很快对疼痛产生了效果。" },
  end: { zh: "结束；末端；目的", en: "the final part, limit, or purpose", ex: "At the end of the road there is a small farm.", exz: "路的尽头有一个小农场。" },
  error: { zh: "错误；差错；误差", en: "a mistake in action, judgment, or calculation", ex: "One small error changed the number.", exz: "一个小错误改变了这个数字。" },
  event: { zh: "事件；活动；比赛项目", en: "something that happens or is planned to happen", ex: "The market day was an important event for the town.", exz: "集市日是这个城镇的重要事件。" },
  example: { zh: "例子；范例；样本", en: "something used to show or explain an idea", ex: "This example makes the rule easy to see.", exz: "这个例子让规则容易理解。" },
  exchange: { zh: "交换；交流；兑换", en: "the act of giving one thing and receiving another", ex: "The exchange of letters continued for many years.", exz: "这种书信交流持续了许多年。" },
  existence: { zh: "存在；生活；生存", en: "the state of being real or alive", ex: "The existence of water made life possible there.", exz: "水的存在使那里有了生活的可能。" },
  expansion: { zh: "扩张；扩大；展开", en: "an increase in size, amount, or range", ex: "The expansion of the road made trade easier.", exz: "道路扩宽让贸易更容易。" },
  experience: { zh: "经验；经历；体验", en: "knowledge gained by living through events", ex: "Her experience in the hospital helped the family.", exz: "她在医院的经验帮助了这个家庭。" },
  expert: { zh: "专家；能手", en: "a person with special knowledge or skill", ex: "An expert looked at the broken engine.", exz: "一位专家查看了坏掉的发动机。" },
  fact: { zh: "事实；实际情况", en: "something known to be true", ex: "The fact was written clearly in the record.", exz: "这个事实被清楚地写在记录里。" },
  fall: { zh: "落下；跌倒；秋天", en: "a drop, a movement downward, or the autumn season", ex: "The fall of the stone made a loud sound.", exz: "石头落下发出很大的声音。" },
  family: { zh: "家庭；家人；族类", en: "a group of related people", ex: "The family worked together in the field.", exz: "这家人在田里一起工作。" },
  father: { zh: "父亲；创始人", en: "a male parent or founder", ex: "Her father taught her how to use the tool.", exz: "她父亲教她怎样使用这个工具。" },
  fear: { zh: "害怕；恐惧；担心", en: "a feeling that danger or pain may come", ex: "Fear kept the child away from the dark room.", exz: "恐惧让孩子远离那个黑暗房间。" },
  feeling: { zh: "感觉；情感；触感", en: "an emotion or a sense from the body", ex: "A feeling of hope came after the good news.", exz: "好消息传来后产生了希望的感觉。" },
  fiction: { zh: "小说；虚构作品；虚构", en: "writing about imagined people or events", ex: "The book of fiction told a story about the sea.", exz: "这本小说讲了一个关于大海的故事。" },
  field: { zh: "田地；场地；领域", en: "open land or an area of work or study", ex: "The field was full of yellow flowers.", exz: "田野里开满了黄色的花。" },
  fight: { zh: "打斗；斗争；争取", en: "a struggle between people, animals, or opposing forces", ex: "The fight stopped when the teacher came.", exz: "老师来了以后打斗停止了。" },
  fire: { zh: "火；火灾；开火", en: "heat and light from burning material", ex: "The fire gave light to the room.", exz: "火给房间带来光亮。" },
  flame: { zh: "火焰；光焰", en: "the bright moving part of a fire", ex: "A small flame burned under the pot.", exz: "锅下面燃着一小团火焰。" },
  flight: { zh: "飞行；航班；逃离", en: "movement through the air or an act of escape", ex: "The flight of birds crossed the evening sky.", exz: "一群鸟的飞行划过傍晚的天空。" },
  flower: { zh: "花；开花植物", en: "the colored part of a plant that may make seed", ex: "A red flower grew near the door.", exz: "门边长着一朵红花。" },
  fold: { zh: "折痕；折叠；褶皱", en: "a bend made by doubling one part over another", ex: "Make one fold in the paper before you cut it.", exz: "裁纸前先把纸折一下。" },
  food: { zh: "食物；食品", en: "things that people or animals eat to live", ex: "The food was simple but good.", exz: "食物简单但很好。" },
  force: { zh: "力量；武力；强迫", en: "strength, power, or pressure that changes movement", ex: "The force of the water moved the wheel.", exz: "水的力量推动了轮子。" },
  form: { zh: "形状；形式；表格", en: "shape, structure, or an official paper to fill in", ex: "The form of the cloud changed in the wind.", exz: "云的形状在风中变化。" },
  friend: { zh: "朋友；友人；支持者", en: "a person one likes and trusts", ex: "A friend came to help with the work.", exz: "一位朋友来帮忙做这项工作。" },
  front: { zh: "前面；正面；前线", en: "the forward part or side of something", ex: "The front of the house faces the road.", exz: "房子的正面朝向道路。" },
  fruit: { zh: "水果；果实；成果", en: "the part of a plant that holds seeds and is often eaten", ex: "Fresh fruit was put in a basket.", exz: "新鲜水果被放进篮子里。" },
  glass: { zh: "玻璃；玻璃杯；镜片", en: "a hard clear material or a drinking vessel made from it", ex: "The glass on the window was clean.", exz: "窗户上的玻璃很干净。" },
  gold: { zh: "金；黄金；金色", en: "a valuable yellow metal or the color like it", ex: "The ring was made of gold.", exz: "这枚戒指是金子做的。" },
  government: { zh: "政府；治理；管理机构", en: "the group or system that directs a country or community", ex: "The government built a new school in the town.", exz: "政府在镇上建了一所新学校。" },
  grain: { zh: "谷物；颗粒；纹理", en: "small hard seeds of food plants or a tiny piece of something", ex: "The farmer stored the grain before winter.", exz: "农民在冬天前储存了谷物。" },
  grass: { zh: "草；草地；牧草", en: "a low green plant that covers fields and lawns", ex: "The grass was wet in the morning.", exz: "早晨的草是湿的。" },
  grip: { zh: "紧握；掌握；控制力", en: "a firm hold with the hand or a strong control over something", ex: "Keep a firm grip on the rope.", exz: "牢牢抓住这根绳子。" },
  group: { zh: "群体；小组；一组", en: "a number of people or things together", ex: "A small group waited near the door.", exz: "一小群人在门边等候。" },
  growth: { zh: "生长；增长；发展", en: "the process of becoming larger, stronger, or more developed", ex: "Warm rain helped the growth of the plants.", exz: "温暖的雨水帮助植物生长。" },
  guide: { zh: "向导；指南；指导", en: "a person or thing that shows the way or gives help", ex: "The guide led us over the hill.", exz: "向导带我们越过小山。" },
  harbor: { zh: "港口；避风港；庇护处", en: "a protected place where ships can stay", ex: "The boat came into the harbor at night.", exz: "船在夜里驶进港口。" },
  harmony: { zh: "和谐；协调；和声", en: "a pleasing agreement between people, sounds, or parts", ex: "The family lived in harmony after the argument ended.", exz: "争论结束后，这家人和睦相处。" },
  hate: { zh: "憎恨；厌恶；强烈反感", en: "a very strong dislike", ex: "Hate can make a small trouble much worse.", exz: "仇恨会让小麻烦变得严重得多。" },
  hearing: { zh: "听力；听觉；听证会", en: "the power to hear or a formal meeting to listen to facts", ex: "His hearing was good even in old age.", exz: "即使年老，他的听力仍然很好。" },
  heat: { zh: "热；高温；热量", en: "the quality that makes something hot", ex: "The heat from the fire dried our coats.", exz: "火的热量烘干了我们的外套。" },
  help: { zh: "帮助；援助；有用的人或物", en: "support given to make work or trouble easier", ex: "Your help made the heavy work easier.", exz: "你的帮助让这项重活轻松了些。" },
  history: { zh: "历史；过去的记录；经历", en: "the record or study of past events", ex: "The old bridge has a long history.", exz: "这座老桥有很长的历史。" },
  hole: { zh: "洞；孔；坑", en: "an empty opening in or through something", ex: "A hole in the roof let in the rain.", exz: "屋顶上的洞让雨水漏了进来。" },
  hope: { zh: "希望；期望；盼望", en: "a feeling that something good may happen", ex: "Hope returned when the letter arrived.", exz: "信到达时，希望又回来了。" },
  hour: { zh: "小时；钟点；某个时刻", en: "a period of sixty minutes", ex: "We waited for one hour at the station.", exz: "我们在车站等了一个小时。" },
  humor: { zh: "幽默；诙谐；心情", en: "the quality that makes things funny or a state of mood", ex: "His gentle humor made the room brighter.", exz: "他温和的幽默让房间里的气氛轻松了。" },
  ice: { zh: "冰；冰块；冰层", en: "water made solid by cold", ex: "Ice covered the small pond.", exz: "冰覆盖了小池塘。" },
  idea: { zh: "想法；主意；概念", en: "a thought, plan, or picture in the mind", ex: "The new idea came during a quiet walk.", exz: "这个新想法是在一次安静散步中产生的。" },
  impulse: { zh: "冲动；推动力；一时的念头", en: "a sudden desire to act or a force that starts movement", ex: "She had an impulse to open the old box.", exz: "她一时冲动想打开那个旧盒子。" },
  increase: { zh: "增加；增长；增量", en: "a rise in number, size, or amount", ex: "There was an increase in trade after the road opened.", exz: "道路开通后，贸易有所增加。" },
  industry: { zh: "工业；行业；勤劳", en: "organized production or steady hard work", ex: "The town grew because of the steel industry.", exz: "这座城镇因钢铁工业而发展起来。" },
  ink: { zh: "墨水；油墨；墨迹", en: "colored liquid used for writing or printing", ex: "Blue ink marked the page.", exz: "蓝色墨水在纸页上留下了标记。" },
  insect: { zh: "昆虫；虫", en: "a small creature with six legs and often wings", ex: "An insect moved across the leaf.", exz: "一只昆虫爬过叶子。" },
  instrument: { zh: "工具；仪器；乐器", en: "a tool for careful work, measurement, or music", ex: "The instrument measured the heat of the water.", exz: "这个仪器测量了水的温度。" },
  insurance: { zh: "保险；保障；保险合同", en: "an agreement that gives protection against loss", ex: "Insurance helped pay for the damage to the shop.", exz: "保险帮助支付了商店受损的费用。" },
  interest: { zh: "兴趣；利益；利息", en: "attention, advantage, or money paid for borrowed money", ex: "Her interest in science began at school.", exz: "她对科学的兴趣始于学校。" },
  invention: { zh: "发明；创造；新发明物", en: "a new thing or method made by thought and work", ex: "The invention made farm work faster.", exz: "这项发明让农活更快完成。" },
  iron: { zh: "铁；熨斗；铁制品", en: "a strong common metal or a tool for pressing cloth", ex: "The gate was made of iron.", exz: "这扇门是铁做的。" },
  jelly: { zh: "果冻；胶状物；冻状食品", en: "a soft food or substance that shakes and holds its shape", ex: "The child put jelly on the bread.", exz: "孩子把果冻抹在面包上。" },
  join: { zh: "连接；加入；接合处", en: "to put together or become part of a group", ex: "The two roads join near the river.", exz: "两条路在河边汇合。" },
  journey: { zh: "旅行；旅程；行程", en: "travel from one place to another", ex: "The journey across the mountains took three days.", exz: "穿越群山的旅程用了三天。" },
  judge: { zh: "法官；裁判；判断", en: "a person who decides in court or the act of deciding value", ex: "The judge listened to every statement.", exz: "法官听取了每一项陈述。" },
  jump: { zh: "跳跃；猛增；突然移动", en: "a quick movement off the ground or a sudden rise", ex: "The boy made a jump over the small stream.", exz: "男孩跳过了那条小溪。" },
  kick: { zh: "踢；踢腿；反冲", en: "a hit made with the foot", ex: "One kick sent the ball over the wall.", exz: "一脚把球踢过了墙。" },
  kiss: { zh: "亲吻；吻；轻触", en: "a touch with the lips to show love or greeting", ex: "The mother gave the baby a kiss.", exz: "母亲亲了婴儿一下。" },
  knowledge: { zh: "知识；了解；学问", en: "facts, information, and understanding gained by learning", ex: "Knowledge of the rules helped the class.", exz: "了解规则帮助了这个班级。" },
  land: { zh: "土地；陆地；国家；着陆", en: "the solid ground, a country area, or the act of coming down", ex: "The boat moved from sea toward land.", exz: "船从海上驶向陆地。" },
  language: { zh: "语言；表达方式；措辞", en: "a system of words used for speaking and writing", ex: "Simple language made the lesson clear.", exz: "简单的语言让课程变得清楚。" },
  laugh: { zh: "笑；笑声；发笑", en: "a sound or action that shows amusement", ex: "A laugh came from the next room.", exz: "隔壁房间传来一阵笑声。" },
  law: { zh: "法律；法则；规律", en: "a rule made by authority or a general rule of nature", ex: "The law protects people in the market.", exz: "法律保护市场里的人们。" },
  lead: { zh: "铅；带领；领先", en: "a heavy soft metal or the act of guiding others", ex: "The guide will lead the group to the harbor.", exz: "向导会带领小组去港口。" },
  learning: { zh: "学习；学问；获得知识", en: "the process of gaining knowledge or skill", ex: "Learning a language takes steady practice.", exz: "学习一门语言需要持续练习。" },
  leather: { zh: "皮革；皮制品", en: "material made from animal skin", ex: "The old bag was made of brown leather.", exz: "这个旧包是棕色皮革做的。" },
  letter: { zh: "字母；信；函件", en: "a written sign in an alphabet or a written message", ex: "She wrote a letter to her brother.", exz: "她给哥哥写了一封信。" },
  level: { zh: "水平；层级；平面；平的", en: "height, rank, or a flat even position", ex: "The water level rose after the rain.", exz: "雨后水位上升了。" },
  lift: { zh: "举起；提升；电梯；搭车", en: "a raising movement or a machine for going up and down", ex: "He gave the box a careful lift.", exz: "他小心地把箱子举了起来。" },
  light: { zh: "光；灯；轻的；点燃", en: "brightness, a lamp, or something not heavy", ex: "A soft light came through the curtain.", exz: "柔和的光透过窗帘照进来。" },
  limit: { zh: "限制；界限；限度", en: "the point or rule beyond which something may not go", ex: "There is a limit to the weight of the bridge.", exz: "这座桥有承重限度。" },
  linen: { zh: "亚麻布；亚麻制品；床上织物", en: "cloth made from flax or household cloth such as sheets", ex: "Clean linen was placed on the bed.", exz: "干净的亚麻床单被铺在床上。" },
  liquid: { zh: "液体；液态物", en: "a substance that flows and takes the shape of its container", ex: "The clear liquid filled the glass.", exz: "透明液体装满了玻璃杯。" },
  list: { zh: "清单；目录；列表", en: "a set of names or items written one after another", ex: "Put bread and milk on the list.", exz: "把面包和牛奶写在清单上。" },
  look: { zh: "看；样子；表情", en: "an act of seeing or the appearance of something", ex: "Take a close look at the small mark.", exz: "仔细看一下那个小标记。" },
  loss: { zh: "损失；丧失；遗失", en: "the state of no longer having something", ex: "The loss of the key delayed the journey.", exz: "钥匙丢失耽误了旅程。" },
  love: { zh: "爱；喜爱；热爱", en: "a strong warm feeling for a person or thing", ex: "Her love of music filled the house.", exz: "她对音乐的热爱充满了整个家。" },
  machine: { zh: "机器；机械装置", en: "a device with parts that uses power to do work", ex: "The machine cut the cloth into equal pieces.", exz: "机器把布裁成相等的几块。" },
  man: { zh: "男人；人；人类", en: "an adult male person or a human being", ex: "The man carried water from the well.", exz: "那个男人从井里挑水。" },
  manager: { zh: "经理；管理者；负责人", en: "a person who directs work or business", ex: "The manager checked the accounts each morning.", exz: "经理每天早晨检查账目。" },
  mark: { zh: "标记；痕迹；分数；做记号", en: "a sign, trace, or score placed on something", ex: "A red mark showed the right answer.", exz: "红色标记指出了正确答案。" },
  market: { zh: "市场；集市；买卖场所", en: "a place or system for buying and selling", ex: "The market was busy on Saturday.", exz: "星期六市场很热闹。" },
  mass: { zh: "大量；团块；质量；群众", en: "a large amount, a body of matter, or ordinary people as a group", ex: "A dark mass of cloud covered the sun.", exz: "一大片乌云遮住了太阳。" },
  meal: { zh: "一餐；饭食；膳食", en: "food eaten at one time", ex: "The evening meal was ready on the table.", exz: "晚饭已经摆在桌上。" },
  measure: { zh: "测量；措施；度量单位", en: "to find size or amount, or an action taken for a purpose", ex: "Use this rule to measure the board.", exz: "用这把尺子量这块木板。" },
  meat: { zh: "肉；食用肉类", en: "the flesh of animals used as food", ex: "The soup had a small piece of meat in it.", exz: "汤里有一小块肉。" },
  meeting: { zh: "会议；会面；聚会", en: "a planned gathering of people", ex: "The meeting began after the bell.", exz: "铃声之后会议开始了。" },
  memory: { zh: "记忆；回忆；记性", en: "the power to keep and bring back past knowledge", ex: "The smell of bread brought back a memory of home.", exz: "面包的气味唤起了家的记忆。" },
  metal: { zh: "金属；金属材料", en: "hard material such as iron, copper, or gold", ex: "The tool was made from strong metal.", exz: "这个工具由坚固的金属制成。" },
  middle: { zh: "中间；中央；中部", en: "the part equally distant from the sides or ends", ex: "Put the table in the middle of the room.", exz: "把桌子放在房间中间。" },
  milk: { zh: "牛奶；乳汁", en: "white liquid produced by female animals and used as food", ex: "The child drank warm milk before sleep.", exz: "孩子睡前喝了热牛奶。" },
  mind: { zh: "头脑；思想；心智；介意", en: "the part of a person that thinks, knows, and remembers", ex: "Keep this rule in mind when you write.", exz: "写作时把这条规则记在心里。" },
  mine: { zh: "矿；矿井；我的东西", en: "a place where minerals are taken from the earth, or something belonging to me", ex: "The mine produced iron for the factory.", exz: "这座矿为工厂生产铁矿石。" },
  minute: { zh: "分钟；片刻；会议记录", en: "a period of sixty seconds or a written note of a meeting", ex: "Wait one minute before you open the door.", exz: "开门前等一分钟。" },
  mist: { zh: "薄雾；水汽；模糊", en: "thin cloud close to the ground or water", ex: "Mist covered the river in the early morning.", exz: "清晨薄雾笼罩着河面。" },
  money: { zh: "钱；货币；资金", en: "coins, notes, or value used to buy things", ex: "She put the money in a safe place.", exz: "她把钱放在安全的地方。" },
  month: { zh: "月；月份；一个月时间", en: "one of the twelve parts of a year", ex: "The work will take one month.", exz: "这项工作需要一个月。" },
  morning: { zh: "早晨；上午；清晨", en: "the early part of the day before noon", ex: "The morning light came through the window.", exz: "晨光从窗户照进来。" },
  mother: { zh: "母亲；妈妈；养育者", en: "a female parent or a woman who cares for a child", ex: "His mother made soup for the family.", exz: "他的母亲为家人做了汤。" },
  motion: { zh: "运动；移动；动议", en: "movement or a formal suggestion in a meeting", ex: "The slow motion of the wheel was easy to see.", exz: "轮子的缓慢转动很容易看清。" },
  mountain: { zh: "山；高山；大量", en: "a very high natural rise of land", ex: "Snow stayed on the top of the mountain.", exz: "山顶上仍然有雪。" },
  move: { zh: "移动；搬家；行动", en: "a change of place or position", ex: "One careful move brought the box inside.", exz: "一个小心的动作把箱子搬了进来。" },
  music: { zh: "音乐；乐曲；乐声", en: "organized sounds made for listening or singing", ex: "Soft music came from the next room.", exz: "隔壁房间传来轻柔的音乐。" },
  name: { zh: "名字；名称；命名", en: "a word by which a person or thing is known", ex: "Write your name at the top of the page.", exz: "把你的名字写在页面上方。" },
  nation: { zh: "国家；民族；国民", en: "a large community of people with a shared land or government", ex: "The nation changed after the long war.", exz: "长期战争之后，这个国家发生了变化。" },
  need: { zh: "需要；需求；必要", en: "a lack of something necessary or useful", ex: "There is a need for clean water in the village.", exz: "这个村子需要干净的水。" },
  news: { zh: "新闻；消息；新近情况", en: "new information about events", ex: "The news of peace reached the town at night.", exz: "和平的消息在夜里传到镇上。" },
  night: { zh: "夜晚；夜间；黑夜", en: "the dark part of the day", ex: "The road was quiet at night.", exz: "夜里这条路很安静。" },
  noise: { zh: "噪声；响声；喧闹", en: "sound, especially loud or unwanted sound", ex: "The noise of the machine stopped suddenly.", exz: "机器的噪声突然停了。" },
  note: { zh: "笔记；便条；音符；注意", en: "a short written record, a message, or a musical sound", ex: "Leave a note on the table.", exz: "在桌上留一张便条。" },
  number: { zh: "数字；数量；号码", en: "a sign or word used for counting or ordering", ex: "The number on the door was hard to read.", exz: "门上的号码很难看清。" },
  observation: { zh: "观察；观察结果；评论", en: "careful looking or a remark based on what is seen", ex: "Her observation of the sky helped the farmers.", exz: "她对天空的观察帮助了农民。" },
  offer: { zh: "提议；报价；提供", en: "something presented for acceptance or the act of presenting it", ex: "His offer of help came at the right time.", exz: "他提出帮助来得正是时候。" },
  oil: { zh: "油；石油；润滑油", en: "a thick liquid used for food, fuel, or machines", ex: "Put a little oil on the wheel.", exz: "在轮子上加一点油。" },
  operation: { zh: "操作；运转；手术；行动", en: "the working of something or a planned action", ex: "The operation of the pump was simple.", exz: "这台泵的操作很简单。" },
  opinion: { zh: "意见；看法；观点", en: "a belief or judgment about something", ex: "Everyone gave an opinion about the plan.", exz: "每个人都对这个计划发表了看法。" },
  order: { zh: "顺序；命令；订单；秩序", en: "arrangement, command, or a request to buy something", ex: "Put the papers in the right order.", exz: "把这些文件按正确顺序放好。" },
  organization: { zh: "组织；机构；安排", en: "a group formed for a purpose or the way parts are arranged", ex: "The organization sent food after the storm.", exz: "暴风雨后，这个组织送来了食物。" },
  ornament: { zh: "装饰品；装饰；点缀", en: "something added to make a thing more attractive", ex: "A small ornament hung near the window.", exz: "窗边挂着一个小装饰品。" },
  owner: { zh: "所有者；主人；业主", en: "a person who has something as property", ex: "The owner of the shop opened the door early.", exz: "店主很早就开了门。" },
  page: { zh: "页；页面；一页纸", en: "one side of a sheet in a book or document", ex: "Turn the page and read the next story.", exz: "翻页读下一个故事。" },
  pain: { zh: "疼痛；痛苦；苦恼", en: "an unpleasant feeling in the body or mind", ex: "The pain in his hand became less after rest.", exz: "休息后，他手上的疼痛减轻了。" },
  paint: { zh: "油漆；颜料；绘画", en: "colored liquid put on a surface or the act of using it", ex: "Fresh paint made the door bright.", exz: "新油漆让门显得很亮。" },
  paper: { zh: "纸；文件；报纸；论文", en: "thin material for writing or printing", ex: "Put the paper under the book.", exz: "把纸放在书下面。" },
  part: { zh: "部分；零件；角色；职责", en: "a piece of a whole or a share in an action", ex: "This small part keeps the machine working.", exz: "这个小零件让机器保持运转。" },
  paste: { zh: "糊状物；浆糊；粘贴", en: "a soft wet substance used for sticking things together", ex: "Use paste to fix the paper to the board.", exz: "用浆糊把纸粘到板上。" },
  payment: { zh: "付款；报酬；支付", en: "money given for goods, work, or a debt", ex: "Payment was made after the work was done.", exz: "工作完成后进行了付款。" },
  peace: { zh: "和平；安宁；平静", en: "a state without war, fighting, or disturbance", ex: "Peace returned to the town after many years.", exz: "多年以后，和平回到了这座城镇。" },
  person: { zh: "人；个人；某人", en: "a human being", ex: "One person stayed to watch the fire.", exz: "有一个人留下来看火。" },
  place: { zh: "地方；位置；场所；放置", en: "a position, area, or location", ex: "This is a good place for a garden.", exz: "这是建花园的好地方。" },
  plant: { zh: "植物；工厂；种植", en: "a living thing that grows in the earth or a place of production", ex: "The plant needed water every morning.", exz: "这株植物每天早晨都需要水。" },
  play: { zh: "游戏；戏剧；玩耍；演奏", en: "amusement, a stage work, or the act of taking part in a game", ex: "The children began to play after school.", exz: "孩子们放学后开始玩耍。" },
  pleasure: { zh: "快乐；乐趣；愉悦", en: "a good feeling of enjoyment or satisfaction", ex: "Reading by the fire gave him pleasure.", exz: "在火边读书给他带来乐趣。" },
  point: { zh: "点；尖端；要点；分数", en: "a small mark, sharp end, or main idea", ex: "The teacher made the point clear.", exz: "老师把要点讲清楚了。" },
  poison: { zh: "毒；毒药；有害物", en: "a substance that can injure or kill living things", ex: "Keep poison away from the children.", exz: "把毒药放在孩子拿不到的地方。" },
  polish: { zh: "抛光；光泽；擦亮剂", en: "shine made by rubbing or a substance used to make shine", ex: "A little polish made the shoes look new.", exz: "一点鞋油让鞋子看起来像新的。" },
  porter: { zh: "搬运工；门房；行李员", en: "a person who carries things or watches an entrance", ex: "The porter carried the heavy bag to the train.", exz: "行李员把沉重的包搬到火车上。" },
  position: { zh: "位置；职位；姿势；立场", en: "place, job, body arrangement, or point of view", ex: "Change the position of the chair near the light.", exz: "把椅子的位置移到灯旁边。" },
  powder: { zh: "粉末；粉；细粉", en: "dry material made of very small pieces", ex: "The white powder was kept in a glass jar.", exz: "白色粉末被装在玻璃罐里。" },
  power: { zh: "力量；权力；动力；电力", en: "strength, control, or energy for work", ex: "The engine lost power on the hill.", exz: "发动机在山坡上失去了动力。" },
  price: { zh: "价格；代价；价钱", en: "the amount of money asked or paid for something", ex: "The price of bread was written on the sign.", exz: "面包的价格写在牌子上。" },
  print: { zh: "印刷；印记；印刷品", en: "marks made by pressing ink or the act of making them", ex: "The print on the page was small but clear.", exz: "页面上的印字很小但清楚。" },
  process: { zh: "过程；程序；加工", en: "a series of actions that produce a result", ex: "The process of making paper took many steps.", exz: "造纸过程有许多步骤。" },
  produce: { zh: "生产；产生；农产品", en: "to make or bring forth something, or food from farms", ex: "The farm will produce more grain this year.", exz: "今年这座农场会生产更多谷物。" },
  profit: { zh: "利润；收益；好处", en: "money gained after costs or a useful result", ex: "The shop made a small profit this month.", exz: "这家店本月获得了一点利润。" },
  property: { zh: "财产；所有物；性质；地产", en: "something owned or a quality that belongs to a thing", ex: "The house and field were his property.", exz: "这所房子和田地是他的财产。" },
  prose: { zh: "散文；普通文字；非诗体文字", en: "ordinary written language, not verse", ex: "The lesson used simple prose for new readers.", exz: "这节课为新读者使用了简单散文。" },
  protest: { zh: "抗议；反对；异议", en: "a strong statement or action against something", ex: "The protest was peaceful but clear.", exz: "这次抗议平和但态度明确。" },
  pull: { zh: "拉；拖；拉力", en: "a force or act that draws something toward oneself", ex: "A strong pull opened the heavy door.", exz: "用力一拉，沉重的门开了。" },
  punishment: { zh: "惩罚；处罚；刑罚", en: "pain or loss given because of wrong action", ex: "The punishment was meant to teach the rule.", exz: "这项惩罚是为了让人明白规则。" },
  purpose: { zh: "目的；用途；意图", en: "the reason for which something is done or made", ex: "The purpose of the sign is to keep people safe.", exz: "这个标志的目的是保护人们安全。" },
  push: { zh: "推；推动；推进", en: "a force or act that moves something away", ex: "One push moved the cart forward.", exz: "一推就让车向前动了。" },
  quality: { zh: "质量；品质；特性", en: "how good something is or a feature it has", ex: "The quality of the cloth was high.", exz: "这块布的质量很好。" },
  question: { zh: "问题；疑问；询问", en: "words used to ask for information", ex: "The child asked a clear question.", exz: "孩子问了一个清楚的问题。" },
  rain: { zh: "雨；雨水；下雨", en: "water falling from clouds", ex: "Rain filled the empty basin.", exz: "雨水装满了空盆。" },
  range: { zh: "范围；山脉；一系列", en: "the distance, limits, or series covered by something", ex: "The mountain range could be seen from the road.", exz: "从路上可以看见那片山脉。" },
  rate: { zh: "比率；速度；价格；费率", en: "a measured amount in relation to time, number, or value", ex: "The rate of growth was slow in winter.", exz: "冬天生长速度很慢。" },
  ray: { zh: "光线；射线；一线", en: "a narrow line of light or energy", ex: "A ray of sun touched the floor.", exz: "一缕阳光照到地板上。" },
  reaction: { zh: "反应；回应；化学反应", en: "what happens in answer to an action or change", ex: "His reaction to the news was quiet.", exz: "他对这个消息的反应很平静。" },
  reading: { zh: "阅读；读物；读数", en: "the act of reading or a value shown by an instrument", ex: "Daily reading made her language stronger.", exz: "每天阅读让她的语言能力更强。" },
  reason: { zh: "理由；原因；理性", en: "a cause, explanation, or power of clear thought", ex: "There was a good reason for the delay.", exz: "这次延误有充分理由。" },
  record: { zh: "记录；档案；唱片；成绩", en: "a written account, stored facts, or the best known result", ex: "The record showed every payment.", exz: "记录显示了每一笔付款。" },
  regret: { zh: "后悔；遗憾；惋惜", en: "sadness about something done or not done", ex: "He felt regret after the angry words.", exz: "说出气话后，他感到后悔。" },
  relation: { zh: "关系；亲属；关联", en: "a connection between people, things, or ideas", ex: "The relation between work and profit was clear.", exz: "工作和利润之间的关系很清楚。" },
  religion: { zh: "宗教；信仰；宗教生活", en: "belief and practice about sacred things or a god", ex: "Religion shaped many rules in the old town.", exz: "宗教影响了这座旧城的许多规则。" },
  representative: { zh: "代表；代理人；有代表性的事物", en: "a person or thing that stands for others", ex: "A representative spoke for the workers.", exz: "一名代表为工人发言。" },
  request: { zh: "请求；要求；申请", en: "an act of asking for something politely or formally", ex: "Her request for help was answered at once.", exz: "她求助的请求立刻得到了回应。" },
  respect: { zh: "尊重；敬意；方面", en: "honor for someone or attention to a particular point", ex: "Respect for the teacher kept the room quiet.", exz: "对老师的尊重让房间保持安静。" },
  rest: { zh: "休息；剩余部分；安放", en: "quiet after work or the part that remains", ex: "After the journey, the horses needed rest.", exz: "旅程之后，马需要休息。" },
  reward: { zh: "奖励；报酬；回报", en: "something given for good work or helpful action", ex: "The reward for honest work was fair payment.", exz: "诚实工作的回报是公平报酬。" },
  rhythm: { zh: "节奏；韵律；律动", en: "a regular pattern of sound or movement", ex: "The rhythm of the song helped the children sing.", exz: "歌曲的节奏帮助孩子们歌唱。" },
  rice: { zh: "米；稻米；米饭", en: "small white or brown grains used as food", ex: "Rice was served with the soup.", exz: "米饭和汤一起端上来。" },
  river: { zh: "河；江；河流", en: "a large natural flow of water", ex: "The river turned beside the town.", exz: "河流在镇旁转弯。" },
  road: { zh: "路；道路；途径", en: "a way for travel between places", ex: "The road crossed a wide field.", exz: "这条路穿过一片宽阔的田地。" },
  roll: { zh: "滚动；卷；名单；面包卷", en: "a turning movement, a rolled form, or a list of names", ex: "The roll of cloth was heavy.", exz: "那卷布很重。" },
  room: { zh: "房间；空间；余地", en: "a part of a building or space for something", ex: "There was room for one more chair.", exz: "还有空间再放一把椅子。" },
  rub: { zh: "摩擦；擦；揉", en: "an act of moving one surface against another", ex: "A quick rub made the metal shine.", exz: "快速擦拭让金属发亮。" },
  rule: { zh: "规则；统治；尺；法则", en: "an instruction, control by authority, or a measuring tool", ex: "The rule was written on the wall.", exz: "规则写在墙上。" },
  run: { zh: "跑；运行；一段连续过程", en: "fast movement on foot or continued operation", ex: "The run to the station made him tired.", exz: "跑去车站让他累了。" },
  salt: { zh: "盐；食盐；盐类", en: "a white substance used to season or preserve food", ex: "Put a little salt in the soup.", exz: "往汤里放一点盐。" },
  sand: { zh: "沙；沙子；沙地", en: "very small grains of stone found on beaches or deserts", ex: "Sand filled his shoes after the walk.", exz: "走完路后，他的鞋里进满了沙子。" },
  scale: { zh: "尺度；刻度；天平；鳞片", en: "a system of size, a measuring mark, or a weighing device", ex: "The map used a small scale.", exz: "这张地图使用了小比例尺。" },
  science: { zh: "科学；科学知识；理科", en: "organized knowledge gained by observation and test", ex: "Science helped explain the change in heat.", exz: "科学帮助解释了热量变化。" },
  sea: { zh: "海；海洋；大量", en: "a large body of salt water", ex: "The sea was calm in the morning.", exz: "早晨的大海很平静。" },
  seat: { zh: "座位；坐处；席位", en: "a place made for sitting", ex: "She found a seat near the window.", exz: "她在窗边找到了一个座位。" },
  secretary: { zh: "秘书；书记；办事员", en: "a person who writes, keeps records, and organizes office work", ex: "The secretary wrote down the decision.", exz: "秘书记下了这个决定。" },
  selection: { zh: "选择；选集；被选之物", en: "the act of choosing or a group chosen", ex: "The selection of books was small but useful.", exz: "这批选书不多但很有用。" },
  self: { zh: "自己；自我；本身", en: "a person's own being or nature", ex: "She learned to trust her self through hard work.", exz: "她通过努力学会相信自己。" },
  sense: { zh: "感觉；意义；理智；判断力", en: "a body power, meaning, or good judgment", ex: "A sense of danger made him stop.", exz: "一种危险感让他停了下来。" },
  servant: { zh: "仆人；佣人；服务者", en: "a person paid to work in another person's house or service", ex: "The servant brought water to the room.", exz: "仆人把水送到房间里。" },
  sex: { zh: "性别；性；性方面", en: "being male or female, or matters of sexual life", ex: "The form asked for the person's sex.", exz: "表格要求填写这个人的性别。" },
  shade: { zh: "阴影；遮荫处；色调", en: "darkness made by blocking light or a slight color difference", ex: "We sat in the shade of the tree.", exz: "我们坐在树荫下。" },
  shake: { zh: "摇动；震动；颤抖", en: "a quick back-and-forth movement", ex: "A shake of the table spilled the milk.", exz: "桌子一晃，牛奶洒了。" },
  shame: { zh: "羞愧；耻辱；可惜的事", en: "a painful feeling about wrong or foolish action", ex: "He felt shame for breaking the glass.", exz: "他为打破玻璃感到羞愧。" },
  shock: { zh: "震惊；冲击；电击", en: "a sudden strong effect on the body or mind", ex: "The bad news gave the family a shock.", exz: "坏消息让这家人震惊。" },
  side: { zh: "边；侧面；一方", en: "one of the surfaces or parts away from the middle", ex: "Stand on the safe side of the road.", exz: "站在道路安全的一侧。" },
  sign: { zh: "标志；迹象；符号；手势", en: "a mark, board, or action that gives information", ex: "The sign pointed toward the harbor.", exz: "标志指向港口。" },
  silk: { zh: "丝；丝绸；丝织品", en: "fine smooth thread or cloth made by silkworms", ex: "The silk dress felt soft in her hand.", exz: "这件丝绸裙子摸起来很柔软。" },
  silver: { zh: "银；银色；银器", en: "a bright valuable metal or the color like it", ex: "The spoon was made of silver.", exz: "这把勺子是银做的。" },
  sister: { zh: "姐妹；姐姐；妹妹", en: "a female child of the same parents", ex: "His sister helped him read the letter.", exz: "他的姐姐帮他读了那封信。" },
  size: { zh: "大小；尺寸；尺码", en: "how large or small something is", ex: "The size of the box was right for the books.", exz: "这个箱子的大小正适合装书。" },
  sky: { zh: "天空；天", en: "the space above the earth seen from the ground", ex: "The sky was clear after the rain.", exz: "雨后天空很晴朗。" },
  sleep: { zh: "睡眠；睡觉；睡意", en: "the natural rest of the body and mind", ex: "Good sleep gave him strength for work.", exz: "良好的睡眠给了他工作的力气。" },
  slip: { zh: "滑倒；纸条；小错误；滑动", en: "a slide, a small piece of paper, or a small mistake", ex: "A slip on the wet floor hurt her foot.", exz: "她在湿地板上一滑，伤了脚。" },
  slope: { zh: "斜坡；坡度；倾斜", en: "land or a surface that goes up or down at an angle", ex: "The slope behind the house was covered with grass.", exz: "房子后面的斜坡长满了草。" },
  smash: { zh: "粉碎；猛撞；破碎声", en: "a hard hit that breaks something", ex: "The smash of the plate made everyone turn.", exz: "盘子摔碎的声音让大家都转过头来。" },
  smell: { zh: "气味；嗅觉；闻", en: "what is sensed by the nose or the power to sense it", ex: "The smell of soup came from the kitchen.", exz: "厨房里传来汤的气味。" },
  smile: { zh: "微笑；笑容", en: "a happy or kind expression made with the mouth", ex: "A smile crossed her face when she saw the child.", exz: "她看见孩子时脸上露出微笑。" },
  smoke: { zh: "烟；烟雾；吸烟", en: "gray or black gas from burning material", ex: "Smoke rose from the small fire.", exz: "小火堆升起了烟。" },
  sneeze: { zh: "喷嚏；打喷嚏", en: "a sudden burst of air from the nose and mouth", ex: "A sneeze came after the dust filled the room.", exz: "灰尘充满房间后，他打了个喷嚏。" },
  snow: { zh: "雪；下雪；积雪", en: "soft white frozen water falling from clouds", ex: "Snow covered the road by morning.", exz: "到早晨，雪覆盖了道路。" },
  soap: { zh: "肥皂；皂；清洁剂", en: "a substance used with water for washing", ex: "Use soap before you wash the wound.", exz: "清洗伤口前先用肥皂。" },
  society: { zh: "社会；社团；群体生活", en: "people living together under shared rules or a group with a purpose", ex: "A fair society protects the weak.", exz: "公平的社会保护弱者。" },
  son: { zh: "儿子；男性后代", en: "a male child in relation to his parents", ex: "Her son carried the basket home.", exz: "她的儿子把篮子提回家。" },
  song: { zh: "歌；歌曲；歌声", en: "words and music sung together", ex: "The song told a story about winter.", exz: "这首歌讲了一个关于冬天的故事。" },
  sort: { zh: "种类；类别；分类", en: "a kind of thing or the act of putting things into groups", ex: "This sort of cloth is strong.", exz: "这种布很结实。" },
  sound: { zh: "声音；声响；听起来", en: "something heard by the ear", ex: "The sound of rain woke the child.", exz: "雨声把孩子吵醒了。" },
  soup: { zh: "汤；羹", en: "liquid food made by cooking meat or vegetables in water", ex: "Hot soup was ready after the long walk.", exz: "长途步行后，热汤已经准备好了。" },
  space: { zh: "空间；空地；间隔；宇宙", en: "empty room, distance, or the area beyond the earth", ex: "Leave space between the two boxes.", exz: "在两个箱子之间留出空间。" },
  stage: { zh: "阶段；舞台；时期", en: "a step in a process or a raised place for performance", ex: "The first stage of the work was complete.", exz: "工作的第一阶段完成了。" },
  start: { zh: "开始；起点；出发", en: "the first part of an action or movement", ex: "The start of the journey was cold and dark.", exz: "旅程开始时又冷又黑。" },
  statement: { zh: "陈述；声明；报表", en: "something said or written clearly as information", ex: "The witness gave a short statement.", exz: "证人作了简短陈述。" },
  steam: { zh: "蒸汽；水汽；蒸", en: "hot water vapor", ex: "Steam rose from the pot.", exz: "蒸汽从锅里升起。" },
  steel: { zh: "钢；钢铁；钢制品", en: "strong metal made from iron and carbon", ex: "The bridge was built with steel.", exz: "这座桥是用钢建成的。" },
  step: { zh: "步；步骤；台阶", en: "a movement of the foot, a stage in work, or a stair", ex: "The next step is to wash the grain.", exz: "下一步是清洗谷物。" },
  stitch: { zh: "针脚；缝线；缝合", en: "a loop of thread made in sewing", ex: "One stitch held the torn cloth together.", exz: "一针把撕破的布缝在了一起。" },
  stone: { zh: "石头；石料；宝石", en: "hard natural mineral material", ex: "A flat stone marked the path.", exz: "一块平石标出了小路。" },
  stop: { zh: "停止；车站；停顿", en: "an end to movement or a place where travel pauses", ex: "The next stop is near the market.", exz: "下一站在市场附近。" },
  story: { zh: "故事；叙述；楼层", en: "an account of events or a level of a building", ex: "The story made the children quiet.", exz: "这个故事让孩子们安静下来。" },
  stretch: { zh: "伸展；一段；延伸", en: "a length of space or time, or the act of making longer", ex: "A long stretch of road crossed the sand.", exz: "一长段道路穿过沙地。" },
  structure: { zh: "结构；建筑物；构造", en: "the way parts are put together or a built thing", ex: "The structure of the roof was simple.", exz: "屋顶的结构很简单。" },
  substance: { zh: "物质；实质；内容", en: "material of a particular kind or the real meaning of something", ex: "The dark substance was not oil.", exz: "这种深色物质不是油。" },
  sugar: { zh: "糖；食糖；甜味物", en: "a sweet substance used in food and drink", ex: "She put sugar in the warm milk.", exz: "她在热牛奶里放了糖。" },
  suggestion: { zh: "建议；暗示；提议", en: "an idea offered for thought or action", ex: "His suggestion improved the plan.", exz: "他的建议改进了计划。" },
  summer: { zh: "夏天；夏季", en: "the warm season of the year", ex: "Summer brought long days and warm rain.", exz: "夏天带来了长白天和暖雨。" },
  support: { zh: "支持；支撑；帮助", en: "help, approval, or something that holds weight", ex: "The wood support kept the roof safe.", exz: "木支撑让屋顶保持安全。" },
  surprise: { zh: "惊讶；意外；使吃惊的事", en: "an unexpected event or feeling", ex: "The letter was a pleasant surprise.", exz: "这封信是一个令人愉快的意外。" },
  swim: { zh: "游泳；游动；眩晕感", en: "movement through water using the body", ex: "A short swim cooled him after work.", exz: "工作后一小段游泳让他凉快下来。" },
  system: { zh: "系统；制度；体系；方法", en: "a set of connected parts or rules working together", ex: "The water system served every house.", exz: "供水系统服务每一户人家。" },
  talk: { zh: "谈话；讲话；讨论", en: "spoken exchange between people", ex: "The talk after dinner was quiet and friendly.", exz: "晚饭后的谈话安静而友好。" },
  taste: { zh: "味道；品味；尝味", en: "the sense by which flavor is known or a personal liking", ex: "The soup had a fresh taste.", exz: "这汤有清新的味道。" },
  tax: { zh: "税；税款；征税", en: "money paid to a government for public needs", ex: "The shop paid its tax at the end of the month.", exz: "这家店在月底缴纳了税款。" },
  teaching: { zh: "教学；教导；教师工作", en: "the work or act of helping others learn", ex: "Good teaching made the rule easy to remember.", exz: "好的教学让这条规则容易记住。" },
  tendency: { zh: "倾向；趋势；习性", en: "a usual direction of behavior or change", ex: "There was a tendency for prices to rise in winter.", exz: "冬天价格有上涨的趋势。" },
  test: { zh: "测试；考试；考验", en: "a way to find out knowledge, quality, or condition", ex: "The test showed that the water was clean.", exz: "测试表明水是干净的。" },
  theory: { zh: "理论；学说；推测", en: "an explanation based on ideas and evidence", ex: "The theory explained the movement of the stars.", exz: "这个理论解释了星星的运动。" },
  thing: { zh: "东西；事情；事物", en: "an object, fact, action, or idea", ex: "Put each thing back in its place.", exz: "把每样东西放回原处。" },
  thought: { zh: "思想；想法；思考", en: "an idea in the mind or the act of thinking", ex: "A careful thought can prevent an error.", exz: "仔细思考可以避免错误。" },
  thunder: { zh: "雷；雷声；轰响", en: "the loud sound that follows lightning", ex: "Thunder rolled over the hills at night.", exz: "夜里雷声滚过群山。" },
  time: { zh: "时间；次数；时刻", en: "the measured flow of events or a particular moment", ex: "There was enough time to finish the letter.", exz: "有足够时间写完这封信。" },
  tin: { zh: "锡；罐头；锡罐", en: "a soft light metal or a container made with it", ex: "The food was kept in a tin on the shelf.", exz: "食物放在架子上的锡罐里。" },
  top: { zh: "顶部；上面；最高处", en: "the highest part or surface of something", ex: "Snow stayed on the top of the wall.", exz: "雪停留在墙顶上。" },
  touch: { zh: "触摸；接触；少量", en: "contact with the hand or a small amount", ex: "A light touch opened the old door.", exz: "轻轻一碰，旧门就开了。" },
  trade: { zh: "贸易；行业；交换", en: "buying, selling, or exchanging goods", ex: "Trade along the river made the town rich.", exz: "沿河贸易让这座城镇富裕起来。" },
  transport: { zh: "运输；交通；运送", en: "the movement of people or goods from one place to another", ex: "River transport carried grain to the city.", exz: "河运把谷物送到城市。" },
  trick: { zh: "诡计；技巧；把戏", en: "a clever act used to deceive or a special skill", ex: "The trick with the card made the children laugh.", exz: "这个纸牌把戏逗笑了孩子们。" },
  trouble: { zh: "麻烦；困难；烦恼", en: "a problem, difficulty, or state of worry", ex: "The broken wheel caused trouble on the road.", exz: "坏掉的轮子在路上造成了麻烦。" },
  turn: { zh: "转动；轮次；转弯；变化", en: "a change of direction, a chance to act, or a rotating movement", ex: "Take the next turn to reach the market.", exz: "在下一个转弯处走就能到市场。" },
  twist: { zh: "扭转；弯曲；转折", en: "a turning or bending movement", ex: "A twist in the rope made it shorter.", exz: "绳子一扭就变短了。" },
  unit: { zh: "单位；单元；部件", en: "one part of a larger whole or a standard amount", ex: "Each unit of the machine had a clear purpose.", exz: "机器的每个单元都有明确用途。" },
  use: { zh: "使用；用途；用处", en: "the act of using something or the purpose it serves", ex: "The use of clean water kept the family healthy.", exz: "使用干净的水让这家人保持健康。" },
  value: { zh: "价值；数值；重要性", en: "worth, importance, or a measured amount", ex: "The value of the old book was high.", exz: "这本旧书的价值很高。" },
  verse: { zh: "诗句；韵文；诗歌", en: "writing arranged with rhythm, often in lines", ex: "The short verse was easy to sing.", exz: "这段短诗很容易唱出来。" },
  vessel: { zh: "容器；船；血管", en: "a container, a ship, or a tube in the body", ex: "The vessel carried oil across the sea.", exz: "这艘船把油运过大海。" },
  view: { zh: "景色；看法；视野", en: "what can be seen or an opinion about something", ex: "The view from the hill showed the whole town.", exz: "从山上可以看到整座城镇的景色。" },
  voice: { zh: "声音；嗓音；发言权", en: "sound made when a person speaks or sings", ex: "Her voice was clear in the large room.", exz: "她的声音在大房间里很清楚。" },
  walk: { zh: "步行；散步；走路", en: "movement on foot or a short journey on foot", ex: "A walk by the river helped him think.", exz: "沿河散步帮助他思考。" },
  war: { zh: "战争；斗争；冲突", en: "armed fighting between countries or large groups", ex: "The war left many houses empty.", exz: "战争让许多房子空了下来。" },
  wash: { zh: "洗；清洗；洗涤", en: "the act of cleaning with water", ex: "A good wash removed the dust from the cloth.", exz: "好好清洗后，布上的灰尘被洗掉了。" },
  waste: { zh: "浪费；废物；荒地", en: "unused material, careless use, or empty land", ex: "Do not waste clean water.", exz: "不要浪费干净的水。" },
  water: { zh: "水；水体；浇水", en: "clear liquid needed by living things", ex: "Water from the well filled the bucket.", exz: "井水装满了水桶。" },
  wave: { zh: "波浪；挥手；起伏", en: "a moving rise on water or a movement of the hand", ex: "A small wave reached the sand.", exz: "一个小浪打到了沙滩上。" },
  wax: { zh: "蜡；蜡状物；打蜡", en: "a soft substance that melts with heat and is used for candles or polish", ex: "Wax from the candle fell on the table.", exz: "蜡烛上的蜡滴到了桌子上。" },
  way: { zh: "路；方式；方向；方法", en: "a path, direction, or manner of doing something", ex: "This way leads to the old bridge.", exz: "这条路通向那座老桥。" },
  weather: { zh: "天气；气候状况", en: "the condition of the air at a time and place", ex: "Cold weather came after the rain.", exz: "雨后来了寒冷的天气。" },
  week: { zh: "周；星期；一周", en: "a period of seven days", ex: "The work will begin next week.", exz: "这项工作下周开始。" },
  weight: { zh: "重量；重物；负担", en: "how heavy something is or a heavy load", ex: "The weight of the stone was too much for one man.", exz: "这块石头的重量一个人搬不动。" },
  wind: { zh: "风；气流；呼吸", en: "moving air", ex: "The wind pushed the smoke across the field.", exz: "风把烟吹过田野。" },
  wine: { zh: "酒；葡萄酒；果酒", en: "an alcoholic drink made from grapes or other fruit", ex: "A bottle of wine stood on the table.", exz: "桌上放着一瓶葡萄酒。" },
  winter: { zh: "冬天；冬季", en: "the cold season of the year", ex: "Winter made the road hard and white.", exz: "冬天让道路变得坚硬而雪白。" },
  woman: { zh: "女人；妇女；成年女性", en: "an adult female person", ex: "The woman carried bread to the market.", exz: "那位妇女把面包带到市场。" },
  wood: { zh: "木头；木材；树林", en: "hard material from trees or a small forest", ex: "Dry wood burned quickly in the fire.", exz: "干木头在火里烧得很快。" },
  wool: { zh: "羊毛；毛线；毛织品", en: "soft hair from sheep used for cloth and thread", ex: "The warm coat was made of wool.", exz: "这件暖和的外套是羊毛做的。" },
  word: { zh: "词；单词；话语", en: "a sound or written sign with meaning", ex: "Write one new word on each card.", exz: "每张卡片上写一个新单词。" },
  work: { zh: "工作；劳动；作品；运转", en: "effort, a job, or something produced", ex: "The work in the field began at sunrise.", exz: "田里的工作在日出时开始。" },
  wound: { zh: "伤口；创伤；伤害", en: "an injury where the body is cut or broken", ex: "Clean the wound before you cover it.", exz: "包扎前先清洗伤口。" },
  writing: { zh: "写作；文字；书写", en: "the act or result of making words on a surface", ex: "Her writing was clear on the clean paper.", exz: "她的字写在干净纸上很清楚。" },
  year: { zh: "年；年份；一年", en: "a period of twelve months", ex: "The tree grew taller each year.", exz: "这棵树每年都长高一些。" }
};
