import { GENERAL_ENRICHMENT } from "./enrichment-general.js";
import { PICTURABLE_ENRICHMENT } from "./enrichment-picturable.js";
import { QUALITIES_ENRICHMENT } from "./enrichment-qualities.js";
import { OPPOSITE_QUALITIES_ENRICHMENT } from "./enrichment-opposite-qualities.js";

export const PUBLIC_ENRICHMENT = {
  ...GENERAL_ENRICHMENT,
  ...PICTURABLE_ENRICHMENT,
  ...QUALITIES_ENRICHMENT,
  ...OPPOSITE_QUALITIES_ENRICHMENT,
  come: { zh: "来；到来；走近说话者或目标", en: "move toward the speaker or toward a named place", ex: "Come to the table before the food is cold.", exz: "饭菜变凉前到桌边来。" },
  get: { zh: "得到；获得；变得；去取", en: "receive, obtain, become, or fetch something", ex: "I will get some water for the child.", exz: "我会给这个孩子取一些水。" },
  give: { zh: "给；交给；提供", en: "put something in another person's possession or care", ex: "Give the note to your mother after class.", exz: "下课后把这张便条给你母亲。" },
  go: { zh: "去；离开；进行", en: "move away, travel, or continue in a direction", ex: "We go across the road when the light is green.", exz: "绿灯时我们穿过马路。" },
  keep: { zh: "保持；保留；照管", en: "hold something, continue a state, or take care of it", ex: "Keep the window open while the room is warm.", exz: "房间暖和时让窗户保持开着。" },
  let: { zh: "让；允许；放任", en: "allow someone or something to do or be done", ex: "Let the young girl put the book on the shelf.", exz: "让这个小女孩把书放到架子上。" },
  make: { zh: "做；制造；使成为", en: "create something or cause a condition to happen", ex: "They make bread in this warm kitchen.", exz: "他们在这个温暖的厨房里做面包。" },
  put: { zh: "放；置于某处", en: "place something in a position", ex: "Put the key under the small stone.", exz: "把钥匙放在小石头下面。" },
  seem: { zh: "似乎；看起来像", en: "appear to be true or to have a certain quality", ex: "The answer may seem simple, but it is important.", exz: "这个答案可能看起来简单，但它很重要。" },
  take: { zh: "拿；带走；接受；花费", en: "get hold of something, carry it, accept it, or use time", ex: "Take this coat with you because the night is cold.", exz: "带上这件外衣，因为夜里很冷。" },
  be: { zh: "是；存在；处于某种状态", en: "exist or have a stated identity or condition", ex: "The water will be warm in a minute.", exz: "水一会儿就会变暖。" },
  do: { zh: "做；执行；完成", en: "perform an action or complete work", ex: "Do the work before you go out to play.", exz: "出去玩之前先把工作做完。" },
  have: { zh: "有；拥有；经历", en: "own, hold, or experience something", ex: "We have enough time for one more question.", exz: "我们还有足够时间再问一个问题。" },
  say: { zh: "说；表达；写明", en: "express words or give a message", ex: "Say the word slowly and then write it down.", exz: "慢慢说出这个词，然后把它写下来。" },
  see: { zh: "看见；理解；会见", en: "notice with the eyes or understand an idea", ex: "I can see the ship from the window.", exz: "我能从窗户看到那艘船。" },
  send: { zh: "发送；派遣；寄出", en: "cause a person, message, or thing to go somewhere", ex: "Send the letter before the end of the day.", exz: "今天结束前把信寄出去。" },
  may: { zh: "可以；可能；表示许可或可能性", en: "show permission or possibility", ex: "You may use my pen if you give it back.", exz: "如果你会还给我，你可以用我的笔。" },
  will: { zh: "将要；愿意；表示未来或意愿", en: "show future action or a person's intention", ex: "I will send the answer tomorrow morning.", exz: "我明天早上会把答案发出去。" },
  about: { zh: "关于；大约；在周围", en: "on the subject of, near in number, or around", ex: "This short story is about a boy and his dog.", exz: "这个短故事是关于一个男孩和他的狗。" },
  across: { zh: "横过；在对面", en: "from one side to the other side", ex: "The bridge goes across the river.", exz: "这座桥横跨河流。" },
  after: { zh: "在……之后；追随", en: "later than something or behind it in order", ex: "Wash your hands after the work is done.", exz: "工作完成之后洗手。" },
  against: { zh: "反对；靠着；逆着", en: "in opposition to or touching for support", ex: "The ladder is against the wall.", exz: "梯子靠在墙上。" },
  among: { zh: "在……之中；在一群里", en: "in the middle of a group or set", ex: "The small house is among tall trees.", exz: "这座小房子在高树之间。" },
  at: { zh: "在；向；以某点为目标", en: "show a place, time, direction, or point", ex: "Meet me at the station at noon.", exz: "中午在车站见我。" },
  before: { zh: "在……之前；在前面", en: "earlier than or in front of something", ex: "Read the question before you give an answer.", exz: "回答之前先读题。" },
  between: { zh: "在两者之间；介于", en: "in the space or relation separating two things", ex: "The road runs between the school and the market.", exz: "这条路在学校和市场之间。" },
  by: { zh: "被；通过；在旁边；不迟于", en: "near, through the action of, or not later than", ex: "The book was written by a young teacher.", exz: "这本书是一位年轻教师写的。" },
  down: { zh: "向下；在低处", en: "toward or in a lower place", ex: "The ball rolled down the hill.", exz: "球从山坡上滚下来。" },
  from: { zh: "从；来自；离开某处", en: "show the starting point, source, or origin", ex: "This letter came from my sister.", exz: "这封信来自我妹妹。" },
  in: { zh: "在……里面；在某段时间内", en: "inside a place, condition, or period", ex: "The apples are in the basket.", exz: "苹果在篮子里。" },
  off: { zh: "离开；脱离；关掉", en: "away from a place, surface, or state of operation", ex: "Take your wet shoes off at the door.", exz: "在门口脱下湿鞋。" },
  on: { zh: "在……上；处于开启状态；关于", en: "touching a surface, operating, or concerning a subject", ex: "The cup is on the table.", exz: "杯子在桌子上。" },
  over: { zh: "在……上方；越过；结束", en: "above, across, or finished", ex: "A dark cloud moved over the town.", exz: "一片乌云移到城镇上方。" },
  through: { zh: "穿过；通过；从头到尾", en: "from one side or end to the other", ex: "The train went through a long tunnel.", exz: "火车穿过一条长隧道。" },
  to: { zh: "到；向；给；表示目的", en: "show direction, receiver, limit, or purpose", ex: "Give this map to the new driver.", exz: "把这张地图给新司机。" },
  under: { zh: "在……下面；少于；受……控制", en: "below something or controlled by it", ex: "The cat is sleeping under the chair.", exz: "猫正在椅子下面睡觉。" },
  up: { zh: "向上；在高处；完成", en: "toward or in a higher place or state", ex: "Stand up when your name is called.", exz: "叫到你的名字时站起来。" },
  with: { zh: "和；带有；使用", en: "together with, having, or using something", ex: "Cut the paper with this knife.", exz: "用这把刀裁纸。" },
  as: { zh: "作为；像；当……时", en: "in the role of, in the same way as, or while", ex: "Use this box as a seat.", exz: "把这个箱子当座位用。" },
  for: { zh: "为了；给；持续；因为", en: "show purpose, receiver, time, or reason", ex: "This warm coat is for the old man.", exz: "这件暖和的外衣是给那位老人用的。" },
  of: { zh: "……的；属于；由……构成", en: "show belonging, material, part, or relation", ex: "A glass of water is on the table.", exz: "桌上有一杯水。" },
  till: { zh: "直到；到……为止", en: "up to the time when something happens", ex: "Wait here till the rain is over.", exz: "在这里等到雨停。" },
  than: { zh: "比；用于比较", en: "used to compare two things", ex: "This road is longer than that one.", exz: "这条路比那条路长。" },
  a: { zh: "一个；一件；某个", en: "used before one non-specific singular thing", ex: "A bird is on the roof.", exz: "屋顶上有一只鸟。" },
  the: { zh: "这；那；特指的人或物", en: "used before a known or particular thing", ex: "The door of the room is open.", exz: "这个房间的门开着。" },
  all: { zh: "全部；所有", en: "the whole number or amount", ex: "All the children came into the room.", exz: "所有孩子都进了房间。" },
  any: { zh: "任何；一些；无论哪一个", en: "one, some, or every member of a group", ex: "Do you have any paper for this note?", exz: "你有写这张便条用的纸吗？" },
  every: { zh: "每一个；所有的", en: "each member of a group without exception", ex: "Every student must read one page.", exz: "每个学生都必须读一页。" },
  little: { zh: "小的；少量的", en: "small in size or amount", ex: "A little fire gave us enough heat.", exz: "一小堆火给了我们足够的热量。" },
  much: { zh: "许多；大量；很", en: "a great amount or degree", ex: "There is much water in the river today.", exz: "今天河里有很多水。" },
  no: { zh: "没有；不是；禁止", en: "not any or a negative answer", ex: "There is no milk in the bottle.", exz: "瓶子里没有牛奶。" },
  other: { zh: "其他的；另一个", en: "different from the one already mentioned", ex: "Put this book with the other books.", exz: "把这本书和其他书放在一起。" },
  some: { zh: "一些；若干；某个", en: "an unknown or limited amount or number", ex: "Some people came early to the meeting.", exz: "一些人很早就来参加会议。" },
  such: { zh: "这样的；如此的", en: "of that kind or degree", ex: "Such a sound may come from the engine.", exz: "这样的声音可能来自发动机。" },
  that: { zh: "那个；那；引导从句", en: "point to a thing, idea, or clause farther away", ex: "That house has a red roof.", exz: "那所房子有红色屋顶。" },
  this: { zh: "这个；这；当前的", en: "point to a near thing, idea, or time", ex: "This question is not hard.", exz: "这个问题不难。" },
  I: { zh: "我；说话者自己", en: "the person who is speaking or writing", ex: "I have a letter for you.", exz: "我有一封给你的信。" },
  he: { zh: "他；男性第三人称", en: "a male person already known or mentioned", ex: "He will take the train tomorrow.", exz: "他明天会坐火车。" },
  you: { zh: "你；你们；听话者", en: "the person or people being spoken to", ex: "You may keep this book for a week.", exz: "你可以把这本书保留一周。" },
  who: { zh: "谁；……的人", en: "ask or refer to a person", ex: "Who put the key under the stone?", exz: "谁把钥匙放在石头下面？" },
  and: { zh: "和；并且；连接并列项", en: "join words, phrases, or clauses", ex: "Bread and butter are on the plate.", exz: "盘子上有面包和黄油。" },
  because: { zh: "因为；由于", en: "give the reason for something", ex: "We stopped because the road was broken.", exz: "我们停下，因为路坏了。" },
  but: { zh: "但是；不过", en: "join two ideas that contrast", ex: "The box is small but very strong.", exz: "这个箱子小，但是很结实。" },
  or: { zh: "或者；还是；否则", en: "show a choice between possibilities", ex: "Do you want tea or water?", exz: "你要茶还是水？" },
  if: { zh: "如果；是否", en: "show a condition or possibility", ex: "If the weather is good, we will go out.", exz: "如果天气好，我们会出去。" },
  though: { zh: "虽然；尽管", en: "show contrast with another statement", ex: "Though the work is hard, we can do it.", exz: "虽然工作很难，我们能完成。" },
  while: { zh: "当……时；而；一段时间", en: "during the time that something happens", ex: "Read while I make the tea.", exz: "我泡茶时你读书。" },
  how: { zh: "怎样；多么；方式", en: "ask about manner, condition, or degree", ex: "How did the glass get broken?", exz: "这个玻璃杯是怎么破的？" },
  when: { zh: "什么时候；当……时", en: "ask or say at what time something happens", ex: "When will the train come?", exz: "火车什么时候来？" },
  where: { zh: "在哪里；到哪里", en: "ask or say in what place something is", ex: "Where did you put the letter?", exz: "你把信放在哪里了？" },
  why: { zh: "为什么；原因", en: "ask for the reason", ex: "Why is the door open?", exz: "门为什么开着？" },
  again: { zh: "再；又一次", en: "one more time or as before", ex: "Please say the word again.", exz: "请再说一遍这个词。" },
  ever: { zh: "曾经；在任何时候", en: "at any time", ex: "Have you ever seen a whale?", exz: "你曾经见过鲸鱼吗？" },
  far: { zh: "远；遥远地", en: "at or to a great distance", ex: "The farm is far from the town.", exz: "农场离城镇很远。" },
  forward: { zh: "向前；前方的", en: "toward the front or future", ex: "Move forward one step.", exz: "向前走一步。" },
  here: { zh: "这里；在此处", en: "in or to this place", ex: "Put the basket here by the door.", exz: "把篮子放在门边这里。" },
  near: { zh: "近；靠近", en: "not far away in place or time", ex: "The school is near the river.", exz: "学校在河流附近。" },
  now: { zh: "现在；此刻", en: "at the present time", ex: "Now we can start the lesson.", exz: "现在我们可以开始上课。" },
  out: { zh: "在外；向外；出来", en: "away from the inside or not at home", ex: "Take the wet clothes out into the sun.", exz: "把湿衣服拿到外面晒太阳。" },
  still: { zh: "仍然；静止的；安静的", en: "continuing, quiet, or without movement", ex: "The water is still after the wind stops.", exz: "风停后，水面平静。" },
  then: { zh: "然后；那时", en: "at that time or next in order", ex: "First read the rule, then write an example.", exz: "先读规则，然后写一个例句。" },
  there: { zh: "那里；存在；用于引出", en: "in or to that place, or used to show existence", ex: "There is a small light in the window.", exz: "窗户里有一盏小灯。" },
  together: { zh: "一起；共同", en: "with one another or in one group", ex: "The family sat together at the table.", exz: "一家人一起坐在桌边。" },
  well: { zh: "好；健康；充分地", en: "in a good way or in good health", ex: "She can write Basic English well.", exz: "她能很好地写基础英语。" },
  almost: { zh: "几乎；差不多", en: "very nearly but not completely", ex: "The work is almost done.", exz: "这项工作差不多完成了。" },
  enough: { zh: "足够；充分", en: "as much or as many as needed", ex: "We have enough bread for everyone.", exz: "我们有足够的面包给每个人。" },
  even: { zh: "甚至；平的；均匀的", en: "including something surprising, or level and equal", ex: "Even a small child can see the moon.", exz: "甚至小孩子也能看到月亮。" },
  not: { zh: "不；表示否定", en: "make a word, phrase, or statement negative", ex: "This road is not safe at night.", exz: "这条路夜里不安全。" },
  only: { zh: "只有；仅仅", en: "no more than or no one except", ex: "Only one train goes north today.", exz: "今天只有一班火车向北开。" },
  quite: { zh: "相当；完全；十分", en: "to a noticeable or complete degree", ex: "The room is quite warm now.", exz: "房间现在相当暖和。" },
  so: { zh: "如此；所以；这样", en: "in this way, to that degree, or therefore", ex: "The basket was heavy, so I put it down.", exz: "篮子很重，所以我把它放下。" },
  very: { zh: "非常；很", en: "to a high degree", ex: "This is a very clear example.", exz: "这是一个非常清楚的例子。" },
  tomorrow: { zh: "明天", en: "the day after today", ex: "We will go to the market tomorrow.", exz: "我们明天会去市场。" },
  yesterday: { zh: "昨天", en: "the day before today", ex: "Yesterday the rain was heavy.", exz: "昨天雨很大。" },
  north: { zh: "北；北方", en: "the direction opposite south", ex: "The ship moved north in the morning.", exz: "早上船向北移动。" },
  south: { zh: "南；南方", en: "the direction opposite north", ex: "Warm wind came from the south.", exz: "暖风从南方吹来。" },
  east: { zh: "东；东方", en: "the direction where the sun rises", ex: "The sun came up in the east.", exz: "太阳从东方升起。" },
  west: { zh: "西；西方", en: "the direction where the sun sets", ex: "The road turns west after the bridge.", exz: "过桥后，道路转向西边。" },
  please: { zh: "请；使高兴", en: "used to make a request polite or to satisfy", ex: "Please put the cup on the table.", exz: "请把杯子放在桌上。" },
  yes: { zh: "是；对；表示同意", en: "an affirmative answer or agreement", ex: "Yes, I will come after breakfast.", exz: "是的，我早饭后会来。" }
};
